# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 6a55c4e
_src_path: gh:makukha/copython
author_email: m.makukha@gmail.com
author_name: Michael Makukha
copyright_year: 2025
docs: github_readme
docs_url: https://github.com/makukha/questionary-cli#readme
github_slug: makukha/questionary-cli
github_url: https://github.com/makukha/questionary-cli
module_name: questionary_cli
openssf_bp_id: ''
project_extras: ''
project_name: questionary-cli
project_script: true
project_script_name: que
project_version: 0.0.0
pypi_package_name: questionary-cli
pypi_url: https://pypi.org/project/questionary-cli
python_version: 3.13.6
python_version_minor: '3.13'
